#!/bin/bash
version=`python3 -c "import actilectrum; print(actilectrum.version.ELECTRUM_VERSION)"`
sig=`./run_actilectrum -w $SIGNING_WALLET signmessage $SIGNING_ADDRESS $version`
echo "{ \"version\":\"$version\", \"signatures\":{ \"$SIGNING_ADDRESS\":\"$sig\"}}"
