#!/bin/bash

set -e

version=`git describe --tags`
echo $version

here=$(dirname "$0")
cd $here/../dist

sftp -oBatchMode=no -b - Actinium-project@actilectrum.org << !
   cd actilectrum-downloads
   mkdir $version
   cd $version
   mput *
   bye
!
